default_install_hook_types: [pre-commit, pre-push]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
  # - repo: https://github.com/koalaman/shellcheck-precommit
  #   rev: v0.11.0
  #   hooks:
  #     - id: shellcheck
  #       exclude: |
  #         (?x)^(
  #           config/zsh/.*
  #         )$
  #       args: [--external-sources]
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.28.0
    hooks:
      - id: gitleaks
        stages:
          - pre-commit
